-- =============================================================================
-- PROJETO COMSOC_IA / COMCIA: CRIAÇÃO E TRANSIÇÃO DE BANCO DE DADOS
-- =============================================================================

-- =============================================================================
-- GRUPO A: CADASTROS BASE E PARÂMETROS
-- =============================================================================

-- 1. Tabela de Estoque de Brindes (Relações Públicas)
CREATE TABLE IF NOT EXISTS comsoc_brindes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_item VARCHAR(255) NOT NULL UNIQUE,
    quantidade_total INTEGER NOT NULL DEFAULT 0,
    quantidade_disponivel INTEGER NOT NULL DEFAULT 0,
    descricao TEXT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =============================================================================
-- GRUPO B: FLUXO DE PAUTAS E DEMANDAS
-- =============================================================================

-- 2. Tabela de Solicitação de Demandas de Comunicação
CREATE TABLE IF NOT EXISTS demandas_comunicacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitante_nome VARCHAR(255) NOT NULL,
    setor VARCHAR(255) NOT NULL,
    contato VARCHAR(100) NOT NULL,
    titulo_evento VARCHAR(255) NOT NULL,
    data_evento DATE NOT NULL,
    hora_evento TIME WITHOUT TIME ZONE NOT NULL,
    local_evento VARCHAR(255) NOT NULL,
    tipo_cobertura JSONB NOT NULL, -- ex: ["foto", "video", "redes"]
    autoridades TEXT NULL,
    score_esforco REAL NOT NULL DEFAULT 0.0,
    sigiloso BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'pendente', -- pendente, ajustes, aprovado, rejeitado
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Histórico de Tramitação e Pareceres de Aprovação (Fluxo Bilateral)
CREATE TABLE IF NOT EXISTS demandas_historico_tramitacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demanda_id BIGINT REFERENCES demandas_comunicacao(id) ON DELETE CASCADE NOT NULL,
    data_hora TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    usuario VARCHAR(255) NOT NULL,
    acao VARCHAR(100) NOT NULL, -- ex: "Aprovado pelo Supervisor", "Ajuste Solicitado"
    parecer TEXT NULL
);

-- =============================================================================
-- GRUPO C: OPERAÇÕES E LOGS DIÁRIOS
-- =============================================================================

-- 4. Tabela de Controle de Cautela de Equipamentos (Câmeras, Lentes, Drones, Baterias)
CREATE TABLE IF NOT EXISTS cautela_equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipamento VARCHAR(255) NOT NULL,
    retirado_por VARCHAR(255) NOT NULL,
    data_retirada TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    data_devolucao TIMESTAMP WITH TIME ZONE NULL,
    pauta_id BIGINT REFERENCES demandas_comunicacao(id) ON DELETE SET NULL NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'retirado' -- retirado, devolvido
);

-- 5. Tabela de Distribuição e Controle de Brindes (Relações Públicas)
CREATE TABLE IF NOT EXISTS comsoc_brindes_distribuicao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brinde_id BIGINT REFERENCES comsoc_brindes_estoque(id) ON DELETE RESTRICT NOT NULL,
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    destinatario_nome VARCHAR(255) NOT NULL, -- Nome do Almirante/Autoridade
    data_entrega DATE NOT NULL DEFAULT CURRENT_DATE,
    demanda_id BIGINT REFERENCES demandas_comunicacao(id) ON DELETE SET NULL NULL,
    entregue_por VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. Tabela de Canal de Notícias e Boletins Oficiais
CREATE TABLE IF NOT EXISTS comsoc_noticias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    conteudo TEXT NOT NULL,
    autor VARCHAR(255) NOT NULL,
    data DATE NOT NULL DEFAULT CURRENT_DATE,
    tags VARCHAR(255) NULL, -- tags separadas por virgula, ex: "Marinha, Defesa, Operações"
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =============================================================================
-- ATUALIZAÇÕES EM SCHEMAS E ESTRUTURAS EXISTENTES
-- =============================================================================

-- Adicionar flag de sigilo e campo para especialidades (compatibilidade COMSOC) se necessário
-- ALTER TABLE Alunos ADD COLUMN IF NOT EXISTS especialidade VARCHAR(100) NULL;
-- ALTER TABLE Alunos ADD COLUMN IF NOT EXISTS ano_letivo VARCHAR(10) NULL DEFAULT '2026';

-- =============================================================================
-- GRUPO D: RECONHECIMENTO FACIAL (INSIGHTFACE)
-- =============================================================================

-- 7. Tabela de Perfis de Embeddings Faciais
CREATE TABLE IF NOT EXISTS face_embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES "Users"(id) ON DELETE CASCADE,
    nome_guerra VARCHAR(100) NOT NULL,
    telegram_id VARCHAR(50) UNIQUE,
    embedding JSONB NOT NULL, -- Vetor 512D do InsightFace
    drive_folder_id VARCHAR(100) NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 8. Tabela de Registro de Fotos Processadas (Google Drive)
CREATE TABLE IF NOT EXISTS processed_photos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name VARCHAR(150) NOT NULL,
    filename VARCHAR(250) NOT NULL,
    drive_file_id VARCHAR(100) NULL,
    drive_link TEXT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 9. Tabela de Correspondências Faciais e Moderação
CREATE TABLE IF NOT EXISTS photo_matches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    photo_id UUID REFERENCES processed_photos(id) ON DELETE CASCADE,
    militar_id UUID REFERENCES "Users"(id) ON DELETE CASCADE,
    similarity REAL NOT NULL,
    status VARCHAR(30) DEFAULT 'aprovado', -- 'aprovado', 'pendente', 'rejeitado'
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
