-- =============================================================================
-- SISGAB / COMSOC_IA - BANCO DE DADOS OFICIAL (POSTGRESQL / SUPABASE)
-- 100% LIMPO - SEM TABELAS DO SISTEMA ANTIGO (SISCOMCA)
-- TODAS AS TABELAS EM CAIXA BAIXA (LOWERCASE / SNAKE_CASE)
-- =============================================================================

-- Habilita extensão de UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- 1. CONFIGURAÇÕES, USUÁRIOS E EFETIVO
-- =============================================================================

-- Configurações Globais do Sistema e Telegram Bot
CREATE TABLE IF NOT EXISTS config (
    chave VARCHAR(100) PRIMARY KEY,
    valor TEXT NOT NULL
);

-- Tabela de Perfis de Usuários Autenticados
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(100) UNIQUE NOT NULL,
    nome VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'operador',
    telegram_id VARCHAR(50) NULL,
    url_foto TEXT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Tabela Principal do Efetivo (Militares e Civis da COMSOC / Gabinete)
CREATE TABLE IF NOT EXISTS efetivo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_guerra VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) NULL,
    senha_hash VARCHAR(255) NULL,
    telegram_id VARCHAR(50) NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'operador',
    posto VARCHAR(100) NULL,
    posto_grad VARCHAR(100) NULL,
    data_nascimento DATE NULL,
    url_foto TEXT NULL,
    setor VARCHAR(100) NULL,
    origem VARCHAR(100) NULL,
    categoria VARCHAR(50) NOT NULL DEFAULT 'militar',
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Solicitações de Cadastro Pendentes (Novos Membros / Solicitantes)
CREATE TABLE IF NOT EXISTS registration_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL,
    nome_completo VARCHAR(255) NOT NULL,
    nome_guerra VARCHAR(100) NOT NULL,
    setor_om VARCHAR(100) NULL DEFAULT 'Externo',
    tipo_usuario VARCHAR(50) NOT NULL DEFAULT 'externo', -- 'externo' ou 'comsoc'
    status VARCHAR(50) NOT NULL DEFAULT 'pendente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Matriz de Permissões por Funcionalidade
CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_key VARCHAR(100) UNIQUE NOT NULL,
    feature_name VARCHAR(255) NOT NULL,
    allowed_roles TEXT NOT NULL
);

-- =============================================================================
-- 2. FLUXO DE DEMANDAS, COBERTURAS E PAUTAS
-- =============================================================================

-- Tabela Principal de Demandas e Eventos de Comunicação Social
CREATE TABLE IF NOT EXISTS demandas_comunicacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitante_nome VARCHAR(255) NOT NULL,
    setor VARCHAR(255) NOT NULL,
    contato VARCHAR(100) NOT NULL,
    titulo_evento VARCHAR(255) NOT NULL,
    data_evento DATE NOT NULL,
    data_fim DATE NULL,
    hora_evento TIME WITHOUT TIME ZONE NOT NULL,
    local_evento VARCHAR(255) NOT NULL,
    tipo_cobertura JSONB NOT NULL DEFAULT '[]'::jsonb,
    autoridades TEXT NULL,
    score_esforco REAL NOT NULL DEFAULT 0.0,
    sigiloso BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'pendente', -- pendente, aprovado, ajustes, rejeitado
    notificar_militar_ids TEXT NULL,
    encarregado_id TEXT NULL,
    arquivo_url TEXT NULL,
    arquivo_nome VARCHAR(255) NULL,
    captacao_entrega VARCHAR(100) DEFAULT 'apenas_captacao_bruto',
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Histórico de Tramitação e Pareceres de Demandas (Fluxo Bilateral)
CREATE TABLE IF NOT EXISTS demandas_historico_tramitacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demanda_id BIGINT REFERENCES demandas_comunicacao(id) ON DELETE CASCADE NOT NULL,
    data_hora TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    usuario VARCHAR(255) NOT NULL,
    acao VARCHAR(100) NOT NULL,
    parecer TEXT NULL
);

-- =============================================================================
-- 3. CAUTELA E ACERVO DE EQUIPAMENTOS
-- =============================================================================

-- Cadastro do Acervo de Equipamentos COMSOC (Câmeras, Lentes, Drones, Baterias)
CREATE TABLE IF NOT EXISTS comsoc_equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) UNIQUE NOT NULL,
    e_pessoal BOOLEAN NOT NULL DEFAULT FALSE,
    descricao TEXT NULL
);

-- Controle de Cautela de Equipamentos (Retirada e Devolução)
CREATE TABLE IF NOT EXISTS cautela_equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipamento VARCHAR(255) NOT NULL,
    retirado_por VARCHAR(255) NOT NULL,
    data_retirada TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    data_devolucao TIMESTAMP WITH TIME ZONE NULL,
    pauta_id BIGINT REFERENCES demandas_comunicacao(id) ON DELETE SET NULL NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'retirado',
    e_pessoal BOOLEAN NOT NULL DEFAULT FALSE,
    event_date DATE NULL
);

-- =============================================================================
-- 4. RELAÇÕES PÚBLICAS, NOTÍCIAS E CALENDÁRIO COMEMORATIVO
-- =============================================================================

-- Estoque de Brindes (Relações Públicas)
CREATE TABLE IF NOT EXISTS comsoc_brindes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_item VARCHAR(255) UNIQUE NOT NULL,
    quantidade_total INTEGER NOT NULL DEFAULT 0,
    quantidade_disponivel INTEGER NOT NULL DEFAULT 0,
    descricao TEXT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Controle de Entrega e Distribuição de Brindes a Autoridades
CREATE TABLE IF NOT EXISTS comsoc_brindes_distribuicao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brinde_id BIGINT REFERENCES comsoc_brindes_estoque(id) ON DELETE RESTRICT NOT NULL,
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    destinatario_nome VARCHAR(255) NOT NULL,
    data_entrega DATE NOT NULL DEFAULT CURRENT_DATE,
    demanda_id BIGINT REFERENCES demandas_comunicacao(id) ON DELETE SET NULL NULL,
    entregue_por VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Canal de Notícias, Releases e Boletins Oficiais
CREATE TABLE IF NOT EXISTS comsoc_noticias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    conteudo TEXT NOT NULL,
    autor VARCHAR(255) NOT NULL,
    data DATE NOT NULL DEFAULT CURRENT_DATE,
    tags VARCHAR(255) NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Datas Comemorativas e Efemérides Militares (Google Calendar / Bot)
CREATE TABLE IF NOT EXISTS datas_comemorativas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia VARCHAR(2) NOT NULL,
    mes VARCHAR(2) NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =============================================================================
-- 5. INTELIGÊNCIA ARTIFICIAL E RECONHECIMENTO FACIAL (INSIGHTFACE)
-- =============================================================================

-- Vetores de Embeddings Faciais (512D) dos Militares
CREATE TABLE IF NOT EXISTS face_embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NULL,
    nome_guerra VARCHAR(100) NOT NULL,
    telegram_id VARCHAR(50) UNIQUE NULL,
    embedding JSONB NOT NULL,
    drive_folder_id VARCHAR(100) NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Registro de Fotos Processadas dos Eventos (Google Drive / Hot)
CREATE TABLE IF NOT EXISTS processed_photos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name VARCHAR(150) NOT NULL,
    filename VARCHAR(250) NOT NULL,
    drive_file_id VARCHAR(100) NULL,
    drive_link TEXT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Correspondências Faciais e Moderação de Mídia
CREATE TABLE IF NOT EXISTS photo_matches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    photo_id UUID REFERENCES processed_photos(id) ON DELETE CASCADE NOT NULL,
    militar_id UUID NULL,
    similarity REAL NOT NULL,
    status VARCHAR(30) DEFAULT 'aprovado',
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =============================================================================
-- 6. OPERAÇÃO DIÁRIA E PAINÉIS DE SERVIÇO
-- =============================================================================

-- Escala Diária da Equipe
CREATE TABLE IF NOT EXISTS escala_diaria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    cargo VARCHAR(100) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    observacao TEXT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Registro de Oficiais e Inspetores de Serviço
CREATE TABLE IF NOT EXISTS oficiais_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cargo VARCHAR(100) NOT NULL,
    ajudante VARCHAR(255) NULL,
    data DATE NOT NULL
);

-- Alertas e Avisos Críticos da TV e Painéis
CREATE TABLE IF NOT EXISTS avisos_criticos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    mensagem TEXT NOT NULL,
    prioridade VARCHAR(50) NOT NULL DEFAULT 'normal',
    turma VARCHAR(100) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ativo',
    data DATE NOT NULL DEFAULT CURRENT_DATE,
    hora TIME WITHOUT TIME ZONE NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE NULL
);

-- Quadro de Tarefas Pendentes da Equipe
CREATE TABLE IF NOT EXISTS tarefas_pendentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT NULL,
    responsavel VARCHAR(255) NOT NULL,
    prioridade VARCHAR(50) NOT NULL DEFAULT 'normal',
    status VARCHAR(50) NOT NULL DEFAULT 'pendente',
    prazo DATE NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE NULL
);

-- =============================================================================
-- INSERÇÃO DE CONFIGURAÇÕES E EFEMÉRIDES INICIAIS
-- =============================================================================

INSERT INTO config (chave, valor) VALUES
    ('linha_base_conceito', '8.5'),
    ('impacto_max_acoes', '1.5'),
    ('tempo_polling_tv', '300'),
    ('cabecalho_tv_title', 'COMSOC • CENTRAL DE OPERAÇÕES E COMANDO DE MÍDIA'),
    ('cabecalho_tv_subtitle', 'SITUAÇÃO CONSOLIDADA E PAUTAS DO DIA'),
    ('codigo_desbloqueio_tv', '1234')
ON CONFLICT (chave) DO NOTHING;

INSERT INTO datas_comemorativas (dia, mes, titulo) VALUES
    ('08', '01', 'Dia do Fotógrafo (COMSOC)'),
    ('07', '03', 'Aniversário do Corpo de Fuzileiros Navais (CFN)'),
    ('11', '06', 'Batalha Naval do Riachuelo (Data Magna da MB)'),
    ('21', '07', 'Dia da Comunicação Social da Marinha'),
    ('23', '10', 'Dia do Aviador / Força Aérea Brasileira'),
    ('19', '11', 'Dia da Bandeira'),
    ('13', '12', 'Dia do Marinheiro (Patrono da MB - Tamandaré)'),
    ('28', '12', 'Dia do Guarda-Marinha')
ON CONFLICT DO NOTHING;
