-- =============================================================================
-- PORTAL DO CONVIDADO — Real-Time Hot Photo Delivery
-- Migração: 02_portal_convidado.sql
-- Descrição: Tabelas para eventos públicos, embeddings faciais por evento,
--            perfis de convidados, entregas e analytics.
-- =============================================================================

-- Extensão para UUIDs (idempotente)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- 1. EVENTOS PÚBLICOS
-- =============================================================================
CREATE TABLE IF NOT EXISTS eventos_publicos (
    id VARCHAR(100) PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_evento DATE NOT NULL,
    local VARCHAR(255) NULL,
    banner_url TEXT NULL,
    drive_folder_id VARCHAR(100) NULL,
    drive_geral_folder_id VARCHAR(100) NULL,
    demanda_id BIGINT NULL,
    status VARCHAR(50) DEFAULT 'ativo' NOT NULL,
    threshold_match REAL DEFAULT 0.45,
    watermark_enabled BOOLEAN DEFAULT TRUE,
    watermark_text VARCHAR(100) DEFAULT 'COMSOC / CGCFN',
    email_template TEXT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE eventos_publicos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Total eventos_publicos" ON eventos_publicos FOR ALL USING (true);

-- =============================================================================
-- 2. EMBEDDINGS DE FOTOS POR EVENTO (1 registro por rosto detectado)
-- =============================================================================
CREATE TABLE IF NOT EXISTS event_photo_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL REFERENCES eventos_publicos(id) ON DELETE CASCADE,
    photo_id UUID NULL REFERENCES processed_photos(id) ON DELETE SET NULL,
    drive_file_id VARCHAR(100) NOT NULL,
    drive_link TEXT NULL,
    photo_filename VARCHAR(250) NULL,
    embedding JSONB NOT NULL,
    bbox JSONB NULL,
    det_score REAL NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_epe_event_id ON event_photo_embeddings(event_id);
CREATE INDEX IF NOT EXISTS idx_epe_drive_file ON event_photo_embeddings(drive_file_id);

ALTER TABLE event_photo_embeddings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Total event_photo_embeddings" ON event_photo_embeddings FOR ALL USING (true);

-- =============================================================================
-- 3. PERFIS FACIAIS DE CONVIDADOS (temporários, por evento)
-- =============================================================================
CREATE TABLE IF NOT EXISTS guest_face_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL REFERENCES eventos_publicos(id) ON DELETE CASCADE,
    session_id VARCHAR(255) NULL,
    email VARCHAR(255) NULL,
    embeddings JSONB NOT NULL DEFAULT '[]'::jsonb,
    notificado BOOLEAN DEFAULT FALSE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    expira_em TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX IF NOT EXISTS idx_gfp_event_id ON guest_face_profiles(event_id);
CREATE INDEX IF NOT EXISTS idx_gfp_email ON guest_face_profiles(email);

ALTER TABLE guest_face_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Total guest_face_profiles" ON guest_face_profiles FOR ALL USING (true);

-- =============================================================================
-- 4. REGISTRO DE ENTREGAS POR E-MAIL
-- =============================================================================
CREATE TABLE IF NOT EXISTS guest_photo_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL REFERENCES eventos_publicos(id) ON DELETE CASCADE,
    guest_email VARCHAR(255) NOT NULL,
    photo_ids TEXT NULL,
    photos_count INT DEFAULT 0,
    enviado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_gpd_event_id ON guest_photo_deliveries(event_id);

ALTER TABLE guest_photo_deliveries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Total guest_photo_deliveries" ON guest_photo_deliveries FOR ALL USING (true);

-- =============================================================================
-- 5. MÉTRICAS / ANALYTICS DO PORTAL
-- =============================================================================
CREATE TABLE IF NOT EXISTS portal_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL REFERENCES eventos_publicos(id) ON DELETE CASCADE,
    tipo VARCHAR(50) NOT NULL,
    session_id VARCHAR(255) NULL,
    metadata JSONB NULL DEFAULT '{}'::jsonb,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pa_event_id ON portal_analytics(event_id);
CREATE INDEX IF NOT EXISTS idx_pa_tipo ON portal_analytics(tipo);

ALTER TABLE portal_analytics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Total portal_analytics" ON portal_analytics FOR ALL USING (true);

-- =============================================================================
-- FIM DA MIGRAÇÃO
-- =============================================================================
